### ISSUE TITLE
DataTable

### ISSUE THREAD

**Issue by icarocrespo** [ProjetoPM/PMST#1]
O sistema apresenta alguns problemas devido ao DataTable. O DataPicker não está funcionando, a tela de Project_Charter é um exemplo. A sidebar também não está realizando as funções de maximizar e minimizar o menu. O design de botões e layout do tooltip foram afetados. 

Estamos com problema também para forçar algumas funcionalidades do DataTable como por exemplo a expansão de um item através do clique no botão verde de "+" que aparece apenas quando a tela está muito pequena. O rodapé começou a subir após a inserção do DataTable.

**Comment by gutogirardon** [comment]
Tentei acessar a Project Charter no menu principal, retornando um erro de que a página não existe, os commits da master estão atualizados? Quando criar uma issue tenta referenciar (linkar na issue) qual classe está com problema/defeito.

**Comment by ArthMalBeck** [comment]
Os import's do datepicker que estavam no footer foram alterados para o header.
